export const API_URL = import.meta.env.VITE_API_URL || 'http://localhost:5000/api';

export const ROLES = {
  EMPLOYEE: 'EMPLOYEE',
  MANAGER: 'MANAGER',
  HR_ADMIN: 'HR_ADMIN',
  LEADERSHIP: 'LEADERSHIP',
};

export const ATTENDANCE_STATUS = {
  PRESENT: 'PRESENT',
  ABSENT: 'ABSENT',
  LATE: 'LATE',
  HOLIDAY: 'HOLIDAY',
  WEEKLY_OFF: 'WEEKLY_OFF',
  LEAVE: 'ON_LEAVE',
};

export const LEAVE_STATUS = {
  PENDING: 'PENDING',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
  CANCELLED: 'CANCELLED',
  WITHDRAWN: 'WITHDRAWN',
};

export const WORKFLOW_TYPES = {
  LEAVE: 'LEAVE',
  REGULARIZATION: 'REGULARIZATION',
  PROFILE_UPDATE: 'PROFILE_UPDATE',
  TRANSFER: 'TRANSFER',
  PROMOTION: 'PROMOTION',
  EXIT: 'EXIT',
};
