export const generatePassword = () => {
  const upper = 'ABCDEFGHJKLMNPQRSTUVWXYZ';
  const lower = 'abcdefghjkmnpqrstuvwxyz';
  const nums = '23456789';
  const special = '@#$!%&';
  const all = upper + lower + nums + special;
  
  let pass = '';
  pass += upper[Math.floor(Math.random() * upper.length)];
  pass += upper[Math.floor(Math.random() * upper.length)];
  pass += lower[Math.floor(Math.random() * lower.length)];
  pass += lower[Math.floor(Math.random() * lower.length)];
  pass += nums[Math.floor(Math.random() * nums.length)];
  pass += nums[Math.floor(Math.random() * nums.length)];
  pass += special[Math.floor(Math.random() * special.length)];
  
  for (let i = 0; i < 3; i++) {
    pass += all[Math.floor(Math.random() * all.length)];
  }
  
  return pass.split('').sort(() => Math.random() - 0.5).join('');
};

export const downloadCredentials = (employee, password) => {
  const firstName = employee.personal?.firstName || '';
  const lastName = employee.personal?.lastName || '';
  const fullName = employee.name || `${firstName} ${lastName}`.trim() || 'Employee';
  const roleName = employee.role || employee.userId?.role || 'EMPLOYEE';
  const deptName = employee.department?.name || employee.department || employee.employment?.departmentId?.name || employee.employment?.department?.name || '—';
  const desigName = employee.designation?.name || employee.designation || employee.employment?.designationId?.name || employee.employment?.designation?.name || '—';
  const locName = employee.location?.name || employee.location || employee.employment?.locationId?.name || employee.employment?.location?.name || '—';
  const emailVal = employee.email || employee.contact?.officialEmail || employee.userId?.email || '—';

  const content = `
=====================================
HRMS ACCOUNT CREDENTIALS
=====================================
Name         : ${fullName}
Employee ID  : ${employee.employeeId || 'Pending'}
Role         : ${roleName}
Department   : ${deptName}
Designation  : ${desigName}
Location     : ${locName}

LOGIN DETAILS
-------------
URL          : http://localhost:5173/login
Email        : ${emailVal}
Password     : ${password || 'Contact HR Admin to reset'}

IMPORTANT: Please change your password after first login.
Generated by HR on: ${new Date().toLocaleString()}
=====================================
  `.trim();
  
  const blob = new Blob([content], { type: 'text/plain' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `${fullName.replace(/\s+/g, '_')}_credentials.txt`;
  a.click();
  URL.revokeObjectURL(url);
};
